.\" Redistribution and use in source and binary forms, with
.\" or without modification, are permitted provided that the
.\" following conditions are met:
.\"
.\" 1. Redistributions of source code must retain this list
.\"    of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce this
.\"    list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
.\" CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\" PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
.\" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.Dd August 30, 2023
.Dt THANM 1
.Os
.Sh NAME
.Nm thanm
.Nd Touhou sprite archive tool
.Sh SYNOPSIS
.Nm
.Op Fl Vfub
.Op Oo Fl l | x | r | c Oc Ar version
.Oo Fl m Ar anmmap Oc Ns Ar ...
.Oo Fl s Ar symbols Oc
.Op Ar archive Op Ar ...
.Sh DESCRIPTION
The
.Nm
utility performs various actions on sprite archives.
The following commands are available:
.Bl -tag -width Ds
.It Nm Fl l Ar version Oo Fl fu Oc Oo Fl m Ar anmmap Oc Ns Ar ... Ar archive
Displays a specification of the archive.
.It Nm Fl x Ar version Oo Fl fub Oc Ar archive Op Ar
Extracts image files.
If no files are specified, all files are extracted.
.It Nm Fl r Ar version Oo Fl fb Oc Ar archive Ar name Ar file
Replaces an entry in the archive.
The name can be obtained by the
.Fl l
command.
.It Nm Fl c Ar version Oo Fl fb Oc Oo Fl m Ar anmmap Oc Ns Ar ... Oo Fl s Ar symbols Oc Ar archive Ar input
Creates a new archive from a specification obtained by the
.Fl l
command.
It will look for referenced image files in the current directory.
.It Nm Fl V
Displays the program version.
.El
.Pp
These options are accepted:
.Bl -tag -width Ds
.It Fl f
The
.Fl f
option can be used to ignore certain errors.
.It Fl m Ar anmmap
The
.Fl m
option can be used to map ins_* to human readable names.
.It Fl s Ar symbols
The
.Fl s
option saves symbol ids to the
.Ar symbols
file.
.It u
The
.Fl u
option gives unique filenames to extracted images.
.It b
The
.Fl b
option disables adding/removing a border to images with x/y offset.
For TH19,
.Nm
won't recompress the image unless it needs to add a border.
JPEGs are never recompressed, regardless of the setting.
.El
.Sh EXIT STATUS
The
.Nm
utility exits with 0 on success, 1 on error.
.Sh "ANMMAP FILE FORMAT"
Anmmap files, which are added with the
.Fl m
option, consist of two kinds of lines: control lines (which start with
.Ql \&! Ns
), and mapping lines.
.Pp
The file starts with
.Ql !anmmap
control line.
The rest of the control lines select the mapping that is being modified:
.Bl -tag -width Ds
.It Ql !ins_names
Instruction names.
This is the default mapping.
.br
Value: identifier
.It Ql !ins_signatures
Instruction signatures.
.br
Value: signature
.It Ql !gvar_names
Global variable names.
.br
Value: identifier
.It Ql !gvar_types
Global variable types.
.br
.No Value: type ( Ns
.Ql $
for integer,
.Ql %
for float)
.El
.Pp
Mapping lines are always of form
.D1 Oo Ar key Oc Oo Ar value Oc
where
.Ar key
is an integer, and
.Ar value
is a string without spaces.
Empty values are allowed.
.Pp
When multiple mappings are specified for the same key or value,
the most recent one has priority.
For example:
.Bd -literal -offset indent
123 foo
123 bar
.Ed
.Pp
will map
.Ql 123
to
.Ql bar Ns
,
.Ql bar
to
.Ql 123 Ns
, and
.Ql foo
to
.Ql 123 Ns
\&.
Note how the first reverse mapping doesn't get removed.
.\" TODO: .Sh EXAMPLES
.Sh SEE ALSO
.Lk https://github.com/thpatch/thtk "Project homepage"
.Sh BUGS
A few files from TH12 and TH13 contain overlapping entries
with different formats.
Dumping and recreating these archives will not result in the same archives.
The affected pixels seem to all have 0 for alpha though.
.Pp
One of the scripts in TH95's front.anm lack a sentinel instruction.
Dumping and recreating this archive will add a sentinel instruction.
.Sh SECURITY CONSIDERATIONS
File names may not be properly sanitized when extracting.
Furthermode, invalid data may not be properly handled.
Do not operate on untrusted files.
