.\" Redistribution and use in source and binary forms, with
.\" or without modification, are permitted provided that the
.\" following conditions are met:
.\"
.\" 1. Redistributions of source code must retain this list
.\"    of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce this
.\"    list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the
.\"    distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
.\" CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\" PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
.\" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.Dd August 25, 2022
.Dt THECL 1
.Os thtk
.Sh NAME
.Nm thecl
.Nd Touhou enemy control language script tool
.Sh SYNOPSIS
.Nm
.Op Fl Vrsx
.Op Oo Fl c | h | d Oc Ar version
.Oo Fl m Ar eclmap Oc Ns Ar ...
.Op Ar input Op Ar output
.Sh DESCRIPTION
The
.Nm
utility (de)compiles ecl scripts.
The following commands are available:
.Bl -tag -width Ds
.It Nm Fl c Ar version Oo Fl s Oc Oo Fl m Ar eclmap Oc Ns Ar ... Op Ar input Op Ar output
Compiles an enemy script.
.It Nm Fl h Ar version Oo Fl m Ar eclmap Oc Ns Ar ... Op Ar input Op Ar output
Creates a header file with forward declarations of all subs in input.
.It Nm Fl d Ar version Oo Fl rx Oc Oo Fl m Ar eclmap Oc Ns Ar ... Op Ar input Op Ar output
Dumps an enemy script.
.It Fl V
Displays the program version.
.El
.Pp
These options are accepted:
.Bl -tag -width Ds
.It Fl m Ar eclmap
The
.Fl m
option can be used to map ins_* to human readable names.
.It Fl r
The
.Fl r
option suppresses code transformations like parameter detection, or expression decompilation.
.It Fl s
The
.Fl s
option enables simple creation mode, which doesn't add any instructions automatically.
.It Fl x
The
.Fl x
option outputs address information when dumping instructions.
Shows both the file offset and the offset relative to the start of the sub.
.El
.Pp
Replace the
.Ar version
option by the enemy script format version requested.
Running the program without a command will list the supported formats.
.Sh EXIT STATUS
The
.Nm
utility exits with 0 on success, 1 on error.
.Sh "ECLMAP FILE FORMAT"
Eclmap files, which are added with the
.Fl m
option, consist of two kinds of lines: control lines (which start with
.Ql \&! Ns
), and mapping lines.
.Pp
The file starts with
.Ql !eclmap
control line. The rest of the control lines select the mapping that is being modified:
.Bl -tag -width Ds
.It Ql !ins_names
Instruction names. This is the default mapping.
.br
Value: identifier
.It Ql !ins_signatures
Instruction signatures.
.br
Value: signature
.It Ql !gvar_names
Global variable names.
.br
Value: identifier
.It Ql !gvar_types
Global variable types.
.br
.No Value: type ( Ns
.Ql $
for integer,
.Ql %
for float)
.It Ql !timeline_ins_names
Timeline instruction names.
.br
Value: identifier
.It Ql !timeline_ins_signatures
Timeline instruction signatures.
.br
Value: signature
.El
.Pp
Mapping lines are always of form
.D1 Oo Ar key Oc Oo Ar value Oc
where
.Ar key
is an integer, and
.Ar value
is a string without spaces.
Empty values are allowed.
.Pp
When multiple mappings are specified for the same key or value, the most recent one has priority. For example:
.Bd -literal -offset indent
123 foo
123 bar
.Ed
.Pp
will map
.Ql 123
to
.Ql bar Ns
,
.Ql bar
to
.Ql 123 Ns
, and
.Ql foo
to
.Ql 123 Ns
\&.
Note how the first reverse mapping doesn't get removed.
.\" TODO: .Sh EXAMPLES
.Sh SEE ALSO
.Lk https://github.com/thpatch/thtk "Project homepage"
.Sh SECURITY CONSIDERATIONS
Invalid data may not be properly handled.
Do not operate on untrusted files.
