name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo
  FLEXBISON_VER: 2.5.25

jobs:
  build-linux:
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Configure CMake
      env:
        CC: ${{matrix.compiler}}
        CXX: ${{matrix.compiler == 'gcc' && 'g++' || 'clang++'}}
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}

  build-win32:
    runs-on: windows-2025
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
    - name: Checkout
      uses: actions/checkout@v7
      with:
        submodules: recursive
    - name: Cache winflexbison
      id: cache-winflexbison
      uses: actions/cache@v6
      with:
        path: win_flex_bison-${{env.FLEXBISON_VER}}.zip
        key: winflexbison-${{env.FLEXBISON_VER}}
    - name: Download winflexbison
      if: steps.cache-winflexbison.outputs.cache-hit != 'true'
      run: curl -OL https://github.com/lexxmark/winflexbison/releases/download/v${{env.FLEXBISON_VER}}/win_flex_bison-${{env.FLEXBISON_VER}}.zip
    - name: Extract winflexbison
      run: |
        mkdir bison
        cd bison
        7z x ../win_flex_bison-${{env.FLEXBISON_VER}}.zip
    - name: Configure CMake
      run: cmake -B build -A ${{matrix.arch == 'x86' && 'Win32' || matrix.arch}} -DBISON_EXECUTABLE=${{github.workspace}}/bison/win_bison.exe -DFLEX_EXECUTABLE=${{github.workspace}}/bison/win_flex.exe -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build build --config ${{env.BUILD_TYPE}}
    - name: Prepare Dist
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{matrix.arch}}
        set THTK_ARCH=${{matrix.arch}}
        call C:\shells\msys2bash.cmd -c "pacman -S --noconfirm --needed --noprogressbar groff dos2unix zip"
        call C:\shells\msys2bash.cmd -c "./make-release.sh ci"
    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: thtk-win32-${{matrix.arch}}
        path: thtk-bin-ci/**/*
    - name: Upload Artifact PDBs
      uses: actions/upload-artifact@v7
      with:
        name: thtk-win32-${{matrix.arch}}-pdbs
        path: thtk-bin-ci-pdbs/**/*
    - name: Upload Artifact to thpatch.net
      if: ${{ env.id_ed25519_secret != '' }}
      env:
        id_ed25519_secret: ${{ secrets.ID_ED25519_SECRET }}
        arch: ${{matrix.arch}}
      shell: powershell
      run: |
        echo $env:id_ed25519_secret | Out-File -encoding ASCII .\id_ed25519

        $acl = Get-Acl .\id_ed25519
        $AccessRule =
          New-Object `
          System.Security.AccessControl.FileSystemAccessRule(
          [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
          [System.Security.AccessControl.FileSystemRights]::Read,
          [System.Security.AccessControl.AccessControlType]::Allow)
        $acl.AddAccessRule($AccessRule)
        $acl.SetAccessRuleProtection($true, # Enable protection (disable inheritance)
          $false) # Don't keep previously inherited rules
        Set-Acl -AclObject $acl -Path .\id_ed25519

        New-Item -ItemType Directory -Path ~\.ssh
        echo @'
        shion.thpatch.net,217.160.187.249,2a02:2479:108:600::1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKXwDLYBTggG6K5tBRsDw0gAwiZTwPTRJkdOV43gUJK1
        shion.thpatch.net,217.160.187.249,2a02:2479:108:600::1 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDOsmSkrJ+L8UE4GtZjZsRvEHgwaGg3Wnn/PsH/m8PM5NdoqUqICpXyzxUyIlr+VJwPH95wLAA8Qh/L0NjlDbl0Sz2+/FxxaQuaINL7Bb7KSSWkKsjGJRu/DVRAzNVFrxj/mzL73k6/m1+4zINrKUx6lkIchgit0VFpihdVJafgfLVFbFa3ADAVtNYsfQgP/YGZISF126OaL8UYC7WDaMxn8Cn5yWBBIzNcMFSjVdSFXYfyVVAF8FSCJ5iVXWjgI3ImWmlQ66uu1AA2hCw2b6qNyTPza6uzez0B7NZ4u/zk1loDRRKcVgTMFjxA37yd/mOkkv+FmhAUiAkQpW/2AVWVwl2l2et3TTj05kvADXIqyhdxtbcyLOcShWmNO+PaoCukA9vihNpTyLN74p1WD/OngTswrYmvQ2BQrB5WDf+ZaehpP9IMq4y4tN6/hW1l2l0BFUGkindNjj5iq8RZg6fKTt+boZ56Q2p/f2Yp0Nn9wjI4zyC9Yswo7Cf8U36mB5E=
        shion.thpatch.net,217.160.187.249,2a02:2479:108:600::1 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDGBZxOX+Iw3xo7avQycu3nFuYafK39B5Y/ixCUtoCY7FP/Kjo8cG5AVfL/v9OXhTwvCK0/2fGFnJorkFL/AaFM=
        '@ | Set-Content -Encoding utf8 ~\.ssh\known_hosts

        cmd /c "ssh -T thcrap-dev-deploy@shion.thpatch.net -i .\id_ed25519 -- ""%GITHUB_REF_NAME%"" ""%arch%"" <thtk-bin-ci.zip"
        Remove-Item .\id_ed25519
